### DISCUSSION TITLE
TypedDocumentNode and typescript-apollo-angular

### DISCUSSION THREAD

**Discussion by Mikastark** [the-guild-org/apollo-angular#1676] [Q&A] [answered]
2.6.0 is released and with it TypedDocumentNode compatibility. But how am i supposed to use it ?

I naively install this packages :

```json
{
    "@graphql-codegen/cli": "^1.21.5",
    "@graphql-codegen/typed-document-node": "^1.18.6",
    "@graphql-codegen/typescript": "^1.22.1",
    "@graphql-codegen/typescript-apollo-angular": "^2.3.1",
    "@graphql-codegen/typescript-operations": "^1.18.0",
    "@graphql-typed-document-node/core": "^3.1.0",
}
```

With this `codegen.yml` file

```yml
overwrite: true
schema: "http://localhost:4000"
documents: "src/**/*.graphql"
generates:
  src/app/core/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      # - "typescript-apollo-angular"
      - "typed-document-node"
```

Note that I have commented *typescript-apollo-angular* because of generation conflict.

And, naturaly, it doesn't generate all query/mutation/subscription services. So before I start migrating my code from using query/mutation/subscription services to basic apollo service use, am I doing something wrong ? Is there a way to generate services that will use TypedDocumentNode ? Are services useless now that query are automatically typed ?

**Comment by dotansimha** [comment, marked as answer]
Hi! 
You can't use both since they will conflict. You should use only `typed-document-node`. 
Then, when you use the generate `...Document` variable with your Apollo-Angular instance, it will be typed automatically. No need for `typescript-apollo-angular`.

**Reply by Mikastark** [reply]
Thanks 🙏 
I did it already and forgot to say in this thread. It works like a charm but it makes query/mutation/subscription services obsolete. That’s good but I think it should be documented.

**Reply by dotansimha** [reply]
@MikaStark where do you think we should document it? Any chance you want to create a PR to update the docs?

**Reply by Mikastark** [reply]
I think it could be great to have a word about it in this two sections :
- https://apollo-angular.com/docs/development-and-testing/developer-tools#code-generation : explain how to use `typed-document-node`
- https://apollo-angular.com/docs/data/services#code-generation : explain that it will not work with `typed-document-node` but you can use regular Apollo service instead with it

Maybe I can create PR later if I have time :)

**Reply by the-ult** [reply]
With Angular, is it recommended to use the `typed-document-node` or `typescript-apollo-angular`? I would expect `typescript-apollo-angular`, since it generates the services. Correct?

And how would it work, if we would use `typed-document-node`?

**Reply by Mikastark** [reply]
In my opinion, typed-document-node is far better as it provided typed gql queries/mutations/subscriptions. You can use it directly with Apollo service and get everything working fine. Generating services is like killing a worm with a bazooka. In one sentence, less code same behavior easier to maintain

**Reply by dotansimha** [reply]
@MikaStark I agree. It makes bundle size smaller, and reduces a lot of boilerplate. 
I would also recommend you to use this codegen preset: https://www.graphql-code-generator.com/plugins/gql-tag-operations-preset , I think it provides the ideal setup.

**Reply by the-ult** [reply]
That sounds great. 
Would be nice if the docs would provide the recommended way with some samples.

**Reply by Mikastark** [reply]
Here is my own setup now, maybe it can help :)

*package.json*
```json
{
  "scripts": {
    "generate": "graphql-codegen"
  },
  "devDependencies": {
     "@graphql-codegen/cli": "^2.0.1",
     "@graphql-codegen/typed-document-node": "^2.0.0",
     "@graphql-codegen/typescript": "^2.0.0",
     "@graphql-codegen/typescript-operations": "^2.0.1",
     "@graphql-typed-document-node/core": "^3.1.0"
  }
}
```

*codegen.yml*
```yml
overwrite: true
schema: ${SCHEMA:"http://localhost:4000/graphql"}
documents: "src/**/*.graphql"
generates:
  src/app/core/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typed-document-node"
```

The only two things you have to do are :
- Create .graphql files containing your requests inside your src/ folder
  - You should create one file per request
  - You should put yours .graphql files inside a graphql/ folder in the proper folder (example: if you are building a blog, put all your post-related requests inside a graphql folder inside the Post module folder)
- Run `npm run generate` to launch codegen. Iy will generate a graphql.ts file inside the src/app/core folder. You can easily use it accross your project. If your API change, re-run the generate command

I don't want to offense anyone, but query/mutation/subscription services should be deprecated in favor of typed documents
